lowercase issue fix

diff --git a/.github/workflows/openshift.yml b/.github/workflows/openshift.yml
--- a/.github/workflows/openshift.yml
+++ b/.github/workflows/openshift.yml
@@ -35,26 +35,29 @@ env:
   APP_NAME: ministry-name-app
   APP_PORT: 8080
 
+  GITHUB_OWNER: vitik-k
+
   IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
   IMAGE_REGISTRY_USER: ${{ github.actor }}
   IMAGE_REGISTRY_PASSWORD: ${{ github.TOKEN }}
 
   # 🖊️ EDIT to specify custom tags for the container image, or default tags will be generated below.
   IMAGE_TAGS: |
-    ghcr.io/${{ github.repository_owner }}/ministry-name-app:latest
-    ghcr.io/${{ github.repository_owner }}/ministry-name-app:${{ github.sha }}
-
-  #ghcr.io/${{ github.repository_owner }}/ministry-name-app:${{ github.ref }}
+    ghcr.io/vitik-k/ministry-name-app:latest
+    ghcr.io/vitik-k/ministry-name-app:${{ github.sha }}
+  
+  #ghcr.io/vitik-k/ministry-name-app:${{ github.ref }}
   # DB config
   POSTGRES_HOST: postgres
   POSTGRES_USER: kat
   POSTGRES_PASSWORD: mypass
   POSTGRES_DB: nameapp
 
+
 on:
   workflow_dispatch:
   push:
-    branches: ["master"]
+    branches: [ "master" ]
 
 jobs:
   # 🖊️ EDIT if you want to run vulnerability check on your project before deploying
@@ -65,10 +68,10 @@ jobs:
   # For guide on adding new starter workflow visit https://docs.github.com/en/github-ae@latest/actions/using-workflows/using-starter-workflows
 
   #crda-scan:
-  #uses: ./.github/workflows/crda.yml
-  #secrets:
-  #CRDA_KEY: ${{ secrets.CRDA_KEY }}
-  # SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}       # Either use SNYK_TOKEN or CRDA_KEY
+    #uses: ./.github/workflows/crda.yml
+    #secrets:
+      #CRDA_KEY: ${{ secrets.CRDA_KEY }}
+      # SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}       # Either use SNYK_TOKEN or CRDA_KEY
   openshift-ci-cd:
     # 🖊️ Uncomment this if you are using CRDA scan step above
     # needs: crda-scan
@@ -82,131 +85,129 @@ jobs:
       SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
 
     steps:
-      - name: Check for required secrets
-        uses: actions/github-script@v6
-        with:
-          script: |
-            const secrets = {
-              OPENSHIFT_SERVER: `${{ secrets.OPENSHIFT_SERVER }}`,
-              OPENSHIFT_TOKEN: `${{ secrets.OPENSHIFT_TOKEN }}`,
-            };
+    - name: Check for required secrets
+      uses: actions/github-script@v6
+      with:
+        script: |
+          const secrets = {
+            OPENSHIFT_SERVER: `${{ secrets.OPENSHIFT_SERVER }}`,
+            OPENSHIFT_TOKEN: `${{ secrets.OPENSHIFT_TOKEN }}`,
+          };
 
-            const GHCR = "ghcr.io";
-            if (`${{ env.IMAGE_REGISTRY }}`.startsWith(GHCR)) {
-              core.info(`Image registry is ${GHCR} - no registry password required`);
+          const GHCR = "ghcr.io";
+          if (`${{ env.IMAGE_REGISTRY }}`.startsWith(GHCR)) {
+            core.info(`Image registry is ${GHCR} - no registry password required`);
+          }
+          else {
+            core.info("A registry password is required");
+            secrets["IMAGE_REGISTRY_PASSWORD"] = `${{ env.IMAGE_REGISTRY_PASSWORD }}`;
+          }
+
+          const missingSecrets = Object.entries(secrets).filter(([ name, value ]) => {
+            if (value.length === 0) {
+              core.error(`Secret "${name}" is not set`);
+              return true;
             }
-            else {
-              core.info("A registry password is required");
-              secrets["IMAGE_REGISTRY_PASSWORD"] = `${{ env.IMAGE_REGISTRY_PASSWORD }}`;
-            }
+            core.info(`✔️ Secret "${name}" is set`);
+            return false;
+          });
 
-            const missingSecrets = Object.entries(secrets).filter(([ name, value ]) => {
-              if (value.length === 0) {
-                core.error(`Secret "${name}" is not set`);
-                return true;
-              }
-              core.info(`✔️ Secret "${name}" is set`);
-              return false;
-            });
+          if (missingSecrets.length > 0) {
+            core.setFailed(`❌ At least one required secret is not set in the repository. \n` +
+              "You can add it using:\n" +
+              "GitHub UI: https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository \n" +
+              "GitHub CLI: https://cli.github.com/manual/gh_secret_set \n" +
+              "Also, refer to https://github.com/redhat-actions/oc-login#getting-started-with-the-action-or-see-example");
+          }
+          else {
+            core.info(`✅ All the required secrets are set`);
+          }
 
-            if (missingSecrets.length > 0) {
-              core.setFailed(`❌ At least one required secret is not set in the repository. \n` +
-                "You can add it using:\n" +
-                "GitHub UI: https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository \n" +
-                "GitHub CLI: https://cli.github.com/manual/gh_secret_set \n" +
-                "Also, refer to https://github.com/redhat-actions/oc-login#getting-started-with-the-action-or-see-example");
-            }
-            else {
-              core.info(`✅ All the required secrets are set`);
-            }
+    - name: Check out repository
+      uses: actions/checkout@v4
 
-      - name: Check out repository
-        uses: actions/checkout@v4
+    - name: Determine app name
+      if: env.APP_NAME == 'ministry-name-app'
+      run: |
+        echo "APP_NAME=$(basename $PWD)" | tee -a $GITHUB_ENV
 
-      - name: Determine app name
-        if: env.APP_NAME == 'ministry-name-app'
-        run: |
-          echo "APP_NAME=$(basename $PWD)" | tee -a $GITHUB_ENV
+    - name: Determine image tags
+      if: env.IMAGE_TAGS == 'ghcr.io/${{ github.repository_owner }}/minnameapp:latest'
+      run: |
+        echo "IMAGE_TAGS=latest ${GITHUB_SHA::12}" | tee -a $GITHUB_ENV
 
-      - name: Determine image tags
-        if: env.IMAGE_TAGS == 'ghcr.io/${{ github.repository_owner }}/minnameapp:latest'
-        run: |
-          echo "IMAGE_TAGS=latest ${GITHUB_SHA::12}" | tee -a $GITHUB_ENV
-
-      - name: Remove any existing .env file
-        run: |
+    - name: Remove any existing .env file
+      run: |
           if [ -f .env]; then rm .env; fi
 
-      - name: Create new .env file for Docker Compose using github secrets
-        run: |
+    - name: Create new .env file for Docker Compose using github secrets
+      run: |
           echo "POSTGRES_USER=${{env.POSTGRES_HOST}}" >> .env
           echo "POSTGRES_USER=${{env.POSTGRES_USER}}" >> .env
           echo "POSTGRES_PASSWORD=${{env.POSTGRES_PASSWORD}}" >> .env
           echo "POSTGRES_DB=${{env.POSTGRES_DB}}" >> .env
           echo "PORT=${{env.APP_PORT}}" >> .env
+          
+    - name: Build from Dockerfile
+      id: build-image
+      uses: redhat-actions/buildah-build@v2
+      with:
+        image: ${{ env.APP_NAME }}
+        tags: |
+          ghcr.io/${{ env.GITHUB_OWNER}}/ministry-name-app:latest
+          ghcr.io/${{ env.GITHUB_OWNER}}/ministry-name-app:${{ github.sha }}
+        dockerfiles: |
+          ./Dockerfile   
 
-      - name: Build from Dockerfile
-        id: build-image
-        uses: redhat-actions/buildah-build@v2
-        with:
-          image: ${{ env.APP_NAME }}
-          tags: |
-            ghcr.io/${{ github.repository_owner }}/ministry-name-app:latest
-            ghcr.io/${{ github.repository_owner }}/ministry-name-app:${{ github.sha }}
-          dockerfiles: |
-            ./Dockerfile
-
-      - name: GHCR login
-        run: |
-          docker login --username ${{ env.IMAGE_REGISTRY_USER }} --password ${{ env.IMAGE_REGISTRY_PASSWORD }} ghcr.io
-
-      - name: Push To GHCR
-        run: |
-          IMAGE_NAME=${{ env.IMAGE_REGISTRY }}/${{ env.APP_NAME }}
-          IMAGE_SHA=${{ github.sha }}
-          TAGS="ghcr.io/vitik-k/ministry-name-app:latest ghcr.io/vitik-k/ministry-name-app:${IMAGE_SHA}"
-          for TAG in $TAGS; do
-            docker tag $IMAGE_NAME:latest $TAG
-            docker push $TAG
+    - name: GHCR login        
+      run: |
+        docker login --username ${{ env.IMAGE_REGISTRY_USER }} --password ${{ env.IMAGE_REGISTRY_PASSWORD }} ghcr.io
+   
+    - name: Push To GHCR
+      run: |
+          for TAG in ${{ env.IMAGE_TAGS}}; do  
+            to
+          docker push $TAG
           done
+          
+    - name: Print image url
+      run: echo "Image pushed as ${{ env.IMAGE_TAGS }}"
+            
 
-      - name: Print image url
-        run: echo "Image pushed as ${{ env.IMAGE_TAGS }}"
+    - name: Install oc
+      uses: redhat-actions/openshift-tools-installer@v1
+      with:
+        oc: 4
 
-      - name: Install oc
-        uses: redhat-actions/openshift-tools-installer@v1
-        with:
-          oc: 4
+    # https://github.com/redhat-actions/oc-login#readme
+    - name: Log in to OpenShift
+      uses: redhat-actions/oc-login@v1
+      with:
+        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
+        openshift_token: ${{ env.OPENSHIFT_TOKEN }}
+        insecure_skip_tls_verify: true
+        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
 
-      # https://github.com/redhat-actions/oc-login#readme
-      - name: Log in to OpenShift
-        uses: redhat-actions/oc-login@v1
-        with:
-          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
-          openshift_token: ${{ env.OPENSHIFT_TOKEN }}
-          insecure_skip_tls_verify: true
-          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+    # This step should create a deployment, service, and route to run your app and expose it to the internet.
+    # https://github.com/redhat-actions/oc-new-app#readme
+    - name: Create and expose app
+      id: deploy-and-expose
+      uses: redhat-actions/oc-new-app@v1
+      with:
+        app_name: ${{ env.APP_NAME }}
+        image: ghcr.io/${{ env.GITHUB_OWNER }}/ministry-name-app:latest
+        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+        port: ${{ env.APP_PORT }}
 
-      # This step should create a deployment, service, and route to run your app and expose it to the internet.
-      # https://github.com/redhat-actions/oc-new-app#readme
-      - name: Create and expose app
-        id: deploy-and-expose
-        uses: redhat-actions/oc-new-app@v1
-        with:
-          app_name: ${{ env.APP_NAME }}
-          image: ghcr.io/${{ github.repository_owner }}/ministry-name-app:latest
-          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
-          port: ${{ env.APP_PORT }}
-
-      - name: Print application URL
-        env:
-          ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
-          SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
-        run: |
-          [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
-          echo
-          echo "======================== Your application is available at: ========================"
-          echo ${{ env.ROUTE }}
-          echo "==================================================================================="
-          echo
-          echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
+    - name: Print application URL
+      env:
+        ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
+        SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
+      run: |
+        [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
+        echo
+        echo "======================== Your application is available at: ========================"
+        echo ${{ env.ROUTE }}
+        echo "==================================================================================="
+        echo
+        echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
